// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8IZkMcIYPWMLyDIXpcyKKUXr225zLuLE',
    appId: '1:790204968493:web:626a50ef1f2340f79dd2a4',
    messagingSenderId: '790204968493',
    projectId: 'flutterfirebaseconnect-34b9c',
    authDomain: 'flutterfirebaseconnect-34b9c.firebaseapp.com',
    storageBucket: 'flutterfirebaseconnect-34b9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8_HrRDBYhLXOcceFc3gaekE_5c-3n8C4',
    appId: '1:790204968493:android:41bfc7c1d73759d09dd2a4',
    messagingSenderId: '790204968493',
    projectId: 'flutterfirebaseconnect-34b9c',
    storageBucket: 'flutterfirebaseconnect-34b9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4wLNIWQb8QkG6LMWY4r-jAM0zvo9uEI',
    appId: '1:790204968493:ios:112d94e8cc673c1d9dd2a4',
    messagingSenderId: '790204968493',
    projectId: 'flutterfirebaseconnect-34b9c',
    storageBucket: 'flutterfirebaseconnect-34b9c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM4wLNIWQb8QkG6LMWY4r-jAM0zvo9uEI',
    appId: '1:790204968493:ios:112d94e8cc673c1d9dd2a4',
    messagingSenderId: '790204968493',
    projectId: 'flutterfirebaseconnect-34b9c',
    storageBucket: 'flutterfirebaseconnect-34b9c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8IZkMcIYPWMLyDIXpcyKKUXr225zLuLE',
    appId: '1:790204968493:web:3b7e791807019a069dd2a4',
    messagingSenderId: '790204968493',
    projectId: 'flutterfirebaseconnect-34b9c',
    authDomain: 'flutterfirebaseconnect-34b9c.firebaseapp.com',
    storageBucket: 'flutterfirebaseconnect-34b9c.firebasestorage.app',
  );

}